<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net9.0</TargetFrameworks>
    <RootNamespace>DBOps</RootNamespace>
    <Authors>Kirill Kravtsov</Authors>
    <Company>DBOps</Company>
    <Version>0.7.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-core" Version="6.0.15" />
  </ItemGroup>

</Project>
