<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <AssemblyName>dbup-tests</AssemblyName>
    <PackageId>dbup-tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>DBOps.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Assent" Version="3.0.1" />
    <PackageReference Include="TestStack.BDDfy" Version="8.0.1.3" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="TestScripts\**\*.sql" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dbops-sqlserver\dbops-sqlserver.csproj" />
    <ProjectReference Include="..\dbops-core\dbops-core.csproj" />
  </ItemGroup>
</Project>